import test from "node:test";
import assert from "node:assert/strict";
import { AppError } from "../../packages/shared-contracts/src/index.ts";
import { resolveTenantRoute } from "../../packages/tenant/src/index.ts";
import { buildSecurityContext, requirePermission } from "../../packages/authorization/src/index.ts";
import { executeGovernedMutation } from "../../packages/platform-core/src/index.ts";
const tenants=[{id:"tenant-a",slug:"alpha",name:"Alpha",status:"active" as const},{id:"tenant-b",slug:"beta",name:"Beta",status:"active" as const}];
const locations=[{id:"loc-a",tenantId:"tenant-a",slug:"main",name:"Alpha Main",status:"active" as const,primary:true},{id:"loc-b",tenantId:"tenant-b",slug:"main",name:"Beta Main",status:"active" as const,primary:true}];
const domains=[{id:"dom-a",tenantId:"tenant-a",locationId:"loc-a",hostname:"alpha.example.com",status:"active" as const},{id:"dom-shadow",tenantId:"tenant-a",locationId:"loc-a",hostname:"beta.ristoairen.com",status:"active" as const}];
const tenantRepo={async findById(id:string){return tenants.find(t=>t.id===id)??null},async findBySlug(slug:string){return tenants.find(t=>t.slug===slug)??null}};
const locationRepo={async findById(id:string){return locations.find(l=>l.id===id)??null},async findPrimaryForTenant(tenantId:string){return locations.find(l=>l.tenantId===tenantId&&l.primary)??null}};
const domainRepo={async findActiveByHostname(hostname:string){return domains.find(d=>d.hostname===hostname&&d.status==="active")??null}};
const tenantMemberships=[{id:"tm-alice-a",tenantId:"tenant-a",identityId:"alice",roleKey:"owner",status:"active" as const},{id:"tm-bob-b",tenantId:"tenant-b",identityId:"bob",roleKey:"admin",status:"active" as const}];
const locationMemberships=[{id:"lm-alice-a",tenantMembershipId:"tm-alice-a",tenantId:"tenant-a",locationId:"loc-a",roleKey:"manager",status:"active" as const},{id:"lm-bob-b",tenantMembershipId:"tm-bob-b",tenantId:"tenant-b",locationId:"loc-b",roleKey:"manager",status:"active" as const}];
const membershipRepo={async findTenantMembership(tenantId:string,identityId:string){return tenantMemberships.find(m=>m.tenantId===tenantId&&m.identityId===identityId)??null},async findLocationMembership(tenantMembershipId:string,locationId:string){return locationMemberships.find(m=>m.tenantMembershipId===tenantMembershipId&&m.locationId===locationId)??null}};
const roleResolver={async platformPermissions(roles:readonly string[]){return roles.includes("platform_admin")?["platform.override_tenant_scope","platform.tenants.manage"]:[]},async tenantPermissions(role:string){if(role==="owner"||role==="admin")return["booking.read","booking.write","tenant.location.all"];return[]},async locationPermissions(role:string){return role==="manager"?["booking.read","booking.write"]:[]}};
async function route(hostname:string){return resolveTenantRoute({hostname,trustedBaseDomain:"ristoairen.com",tenants:tenantRepo,locations:locationRepo,domains:domainRepo})}
async function aliceContext(){return buildSecurityContext({principal:{identityId:"alice",providerKey:"test",providerSubject:"alice",platformRoles:[]},route:await route("alpha.example.com"),memberships:membershipRepo,roles:roleResolver,entitlements:["risto.booking"],correlationId:"corr-1"})}
test("exact custom domain resolves to Tenant and Location",async()=>{const r=await route("ALPHA.EXAMPLE.COM:443");assert.equal(r.tenant.id,"tenant-a");assert.equal(r.location.id,"loc-a");assert.equal(r.source,"custom-domain")});
test("trusted platform subdomain resolves slug only under configured base domain",async()=>{const r=await route("beta.ristoairen.com");assert.equal(r.tenant.id,"tenant-b");assert.equal(r.location.id,"loc-b")});
test("trusted platform namespace cannot be shadowed by custom-domain registry",async()=>{const r=await route("beta.ristoairen.com");assert.equal(r.tenant.id,"tenant-b");assert.equal(r.source,"trusted-platform-subdomain")});
test("unknown hostname fails closed and never falls back to a default tenant",async()=>{await assert.rejects(()=>route("unknown.example.net"),(e:unknown)=>e instanceof AppError&&e.code==="TENANT_RESOLUTION_FAILED")});
test("nested untrusted platform hostname fails closed",async()=>{await assert.rejects(()=>route("evil.alpha.ristoairen.com"),(e:unknown)=>e instanceof AppError&&e.code==="TENANT_RESOLUTION_FAILED")});
test("tenant admin is not platform admin and cannot enter another tenant without membership",async()=>{const beta=await route("beta.ristoairen.com");await assert.rejects(()=>buildSecurityContext({principal:{identityId:"alice",providerKey:"test",providerSubject:"alice",platformRoles:["admin"]},route:beta,memberships:membershipRepo,roles:roleResolver,entitlements:[]}),(e:unknown)=>e instanceof AppError&&e.code==="MEMBERSHIP_REQUIRED")});
test("explicit platform_admin permission may cross tenant boundary",async()=>{const beta=await route("beta.ristoairen.com");const c=await buildSecurityContext({principal:{identityId:"platform-1",providerKey:"test",providerSubject:"platform-1",platformRoles:["platform_admin"]},route:beta,memberships:membershipRepo,roles:roleResolver,entitlements:[]});assert.equal(c.tenantId,"tenant-b");assert.ok(c.platformPermissions.includes("platform.override_tenant_scope"))});
test("resource tenant mismatch is denied for a normal tenant member",async()=>{const c=await aliceContext();assert.throws(()=>requirePermission(c,"booking.write",{tenantId:"tenant-b",locationId:"loc-b"}),(e:unknown)=>e instanceof AppError&&e.code==="TENANT_SCOPE_VIOLATION")});
test("missing entitlement blocks governed mutation",async()=>{const c={...(await aliceContext()),entitlements:[]};await assert.rejects(()=>executeGovernedMutation({context:c,permissionKey:"booking.write",entitlementKey:"risto.booking",resourceScope:{tenantId:"tenant-a",locationId:"loc-a"},actionKey:"booking.create",unitOfWork:{async transaction(fn){return fn({async audit(){},async outbox(){}})}},async mutate(){return{id:"booking-1"}}}),(e:unknown)=>e instanceof AppError&&e.code==="ENTITLEMENT_REQUIRED")});
test("governed mutation writes audit and outbox in same unit of work",async()=>{const c=await aliceContext();const audit:unknown[]=[];const outbox:unknown[]=[];const result=await executeGovernedMutation({context:c,permissionKey:"booking.write",entitlementKey:"risto.booking",resourceScope:{tenantId:"tenant-a",locationId:"loc-a"},actionKey:"booking.create",resource:{type:"Booking",id:"booking-1"},unitOfWork:{async transaction(fn){return fn({async audit(record){audit.push(record)},async outbox(event){outbox.push(event)}})}},async mutate(_tx,sc){return{id:"booking-1",tenantId:sc.tenantId,locationId:sc.locationId}},event:(b)=>({eventType:"booking.created",aggregateType:"Booking",aggregateId:b.id,payloadVersion:1,payload:b})});assert.deepEqual(result,{id:"booking-1",tenantId:"tenant-a",locationId:"loc-a"});assert.equal(audit.length,1);assert.equal(outbox.length,1)});
test("client-provided tenant_id is not authoritative",async()=>{const c=await aliceContext();const malicious={tenant_id:"tenant-b",location_id:"loc-b",guestName:"Test"};const stored=await executeGovernedMutation({context:c,permissionKey:"booking.write",entitlementKey:"risto.booking",resourceScope:{tenantId:c.tenantId,locationId:c.locationId},actionKey:"booking.create",unitOfWork:{async transaction(fn){return fn({async audit(){},async outbox(){}})}},async mutate(_tx,sc){return{guestName:malicious.guestName,tenantId:sc.tenantId,locationId:sc.locationId}}});assert.equal(stored.tenantId,"tenant-a");assert.equal(stored.locationId,"loc-a")});
