import type { Pool, PoolClient } from "pg";
import { AppError, type PlatformSecurityContext, type SecurityContext } from "../../shared-contracts/src/index.ts";
import type {
  CapabilityAiAccessMode, CapabilityAuditLevel, CapabilityLifecycleAction, CapabilityLifecycleTransaction, CapabilityLifecycleUnitOfWork, CapabilityMutationResult,
  CapabilityProjection, CapabilityScopeKind, CapabilityStatus, CurrentCapabilityAvailabilityResolver, CurrentCapabilityAvailabilityRow,
  FeatureFlagLifecycleAction, FeatureFlagMutationResult, FeatureFlagOverrideAction, FeatureFlagOverrideMutationResult, FeatureFlagOverrideProjection,
  FeatureFlagOverrideStatus, FeatureFlagOverrideSubjectKind, FeatureFlagProjection, FeatureFlagStatus, PlatformCapabilityQueryStore
} from "../../capabilities/src/index.ts";

function role(v:string){if(!/^[a-z_][a-z0-9_]*$/.test(v))throw new Error("Unsafe PostgreSQL role identifier");return v;}
function translate(error:unknown):unknown{const e=error as {code?:string;message?:string;constraint?:string};
  if(e.code==="42501")return new AppError("PERMISSION_DENIED","Capability control-plane authority denied");
  if(e.code==="P0002")return new AppError("NOT_FOUND","Capability or Feature Flag resource not found");
  if(e.code==="P0001"&&e.message?.includes("AIRENOS_IDEMPOTENCY_CONFLICT"))return new AppError("IDEMPOTENCY_CONFLICT","Capability idempotency key reused with different input");
  if(e.code==="P0001")return new AppError("CONFLICT","Capability/Feature lifecycle transition conflict");
  if(e.code==="23505")return new AppError("CONFLICT","Capability or Feature Flag key already exists");
  if(["22023","23502","23503","23514","22P02"].includes(e.code??""))return new AppError("VALIDATION_FAILED","Capability input violated PostgreSQL contract");
  return error;}
const iso=(v:unknown)=>v==null?undefined:new Date(String(v)).toISOString();
const arr=(v:unknown)=>Array.isArray(v)?v.map(String):[];
function capability(o:any):CapabilityProjection{return {id:String(o.id),capabilityKey:String(o.capabilityKey??o.capability_key),name:String(o.name),description:o.description==null?undefined:String(o.description),status:String(o.status) as CapabilityStatus,scopeKind:String(o.scopeKind??o.scope_kind) as CapabilityScopeKind,requiredEntitlements:arr(o.requiredEntitlements??o.required_entitlements),requiredPermissions:arr(o.requiredPermissions??o.required_permissions),featureFlagKey:(o.featureFlagKey??o.feature_flag_key)==null?undefined:String(o.featureFlagKey??o.feature_flag_key),auditLevel:String(o.auditLevel??o.audit_level) as CapabilityAuditLevel,aiAccessMode:String(o.aiAccessMode??o.ai_access_mode) as CapabilityAiAccessMode,createdAt:new Date(String(o.createdAt??o.created_at)).toISOString(),updatedAt:new Date(String(o.updatedAt??o.updated_at)).toISOString(),activatedAt:iso(o.activatedAt??o.activated_at),retiredAt:iso(o.retiredAt??o.retired_at)};}
function flag(o:any):FeatureFlagProjection{return {id:String(o.id),featureFlagKey:String(o.featureFlagKey??o.feature_flag_key),description:o.description==null?undefined:String(o.description),status:String(o.status) as FeatureFlagStatus,enabledDefault:Boolean(o.enabledDefault??o.enabled_default),validFrom:iso(o.validFrom??o.valid_from),validUntil:iso(o.validUntil??o.valid_until),createdAt:new Date(String(o.createdAt??o.created_at)).toISOString(),updatedAt:new Date(String(o.updatedAt??o.updated_at)).toISOString(),retiredAt:iso(o.retiredAt??o.retired_at)};}
function override(o:any):FeatureFlagOverrideProjection{return {id:String(o.id),featureFlagKey:String(o.featureFlagKey??o.feature_flag_key),subjectKind:String(o.subjectKind??o.subject_kind) as FeatureFlagOverrideSubjectKind,tenantId:String(o.tenantId??o.tenant_id),locationId:(o.locationId??o.location_id)==null?undefined:String(o.locationId??o.location_id),enabled:Boolean(o.enabled),validFrom:iso(o.validFrom??o.valid_from),validUntil:iso(o.validUntil??o.valid_until),reasonCode:String(o.reasonCode??o.reason_code),status:String(o.status) as FeatureFlagOverrideStatus,createdAt:new Date(String(o.createdAt??o.created_at)).toISOString(),updatedAt:new Date(String(o.updatedAt??o.updated_at)).toISOString(),removedAt:iso(o.removedAt??o.removed_at)};}

class Tx implements CapabilityLifecycleTransaction{private readonly c:PoolClient;constructor(c:PoolClient){this.c=c;}
  async mutateCapability(input:any):Promise<CapabilityMutationResult>{const r=await this.c.query("SELECT security.platform_mutate_capability($1::jsonb) result",[JSON.stringify(input)]);const x=r.rows[0]?.result;if(!x)throw new AppError("INTERNAL_ERROR","Capability mutation returned no result");return {capability:capability(x.resource),replayed:Boolean(x.replayed)};}
  async mutateFeatureFlag(input:any):Promise<FeatureFlagMutationResult>{const r=await this.c.query("SELECT security.platform_mutate_feature_flag($1::jsonb) result",[JSON.stringify(input)]);const x=r.rows[0]?.result;if(!x)throw new AppError("INTERNAL_ERROR","Feature Flag mutation returned no result");return {featureFlag:flag(x.resource),replayed:Boolean(x.replayed)};}
  async mutateFeatureFlagOverride(input:any):Promise<FeatureFlagOverrideMutationResult>{const r=await this.c.query("SELECT security.platform_mutate_feature_flag_override($1::jsonb) result",[JSON.stringify(input)]);const x=r.rows[0]?.result;if(!x)throw new AppError("INTERNAL_ERROR","Feature Flag override mutation returned no result");return {override:override(x.resource),replayed:Boolean(x.replayed)};}
}
export class PostgresCapabilityControlPlaneStore implements CapabilityLifecycleUnitOfWork,PlatformCapabilityQueryStore,CurrentCapabilityAvailabilityResolver{
  private readonly pool:Pool;private readonly cpRole:string;private readonly appRole:string;constructor(pool:Pool,cpRole="airen_control_plane",appRole="airen_app"){this.pool=pool;this.cpRole=cpRole;this.appRole=appRole;}
  async transaction<T>(fn:(tx:CapabilityLifecycleTransaction)=>Promise<T>,context:PlatformSecurityContext){const c=await this.openPlatform(context);try{const result=await fn(new Tx(c));await c.query("COMMIT");return result;}catch(e){await c.query("ROLLBACK");throw translate(e);}finally{c.release();}}
  async getCapability(k:string,context:PlatformSecurityContext){return this.platformQuery(context,"SELECT security.platform_get_capability($1) result",[k],r=>r?capability(r):null);}
  async listCapabilities(input:{status?:CapabilityStatus;scopeKind?:CapabilityScopeKind;afterKey?:string;limit?:number},context:PlatformSecurityContext){return this.platformQuery(context,"SELECT * FROM security.platform_list_capabilities($1,$2,$3,$4)",[input.status??null,input.scopeKind??null,input.afterKey??null,input.limit??50],r=>r.map((x:any)=>capability(x)));}
  async getFeatureFlag(k:string,context:PlatformSecurityContext){return this.platformQuery(context,"SELECT security.platform_get_feature_flag($1) result",[k],r=>r?flag(r):null);}
  async listFeatureFlags(input:{status?:FeatureFlagStatus;afterKey?:string;limit?:number},context:PlatformSecurityContext){return this.platformQuery(context,"SELECT * FROM security.platform_list_feature_flags($1,$2,$3)",[input.status??null,input.afterKey??null,input.limit??50],r=>r.map((x:any)=>flag(x)));}
  async listFeatureFlagOverrides(input:{featureFlagKey?:string;tenantId?:string;subjectKind?:FeatureFlagOverrideSubjectKind;status?:FeatureFlagOverrideStatus;limit?:number},context:PlatformSecurityContext){return this.platformQuery(context,"SELECT * FROM security.platform_list_feature_flag_overrides($1,$2,$3,$4,$5)",[input.featureFlagKey??null,input.tenantId??null,input.subjectKind??null,input.status??null,input.limit??50],r=>r.map((x:any)=>override(x)));}
  async resolveCurrentCapabilityAvailability(context:SecurityContext):Promise<readonly CurrentCapabilityAvailabilityRow[]>{const c=await this.pool.connect();try{await c.query("BEGIN");await c.query(`SET LOCAL ROLE ${role(this.appRole)}`);await c.query("SELECT set_config('airen.identity_id',$1,true),set_config('airen.tenant_id',$2,true),set_config('airen.location_id',$3,true),set_config('airen.correlation_id',$4,true)",[context.actorIdentityId,context.tenantId,context.locationId,context.correlationId]);const r=await c.query("SELECT * FROM security.resolve_current_capability_availability()");await c.query("COMMIT");return r.rows.map((x:any)=>({capabilityKey:String(x.capability_key),scopeKind:String(x.scope_kind) as CapabilityScopeKind,requiredPermissions:arr(x.required_permissions),available:Boolean(x.available),denialReasons:arr(x.denial_reasons)}));}catch(e){await c.query("ROLLBACK");throw translate(e);}finally{c.release();}}
  private async platformQuery<T>(context:PlatformSecurityContext,sql:string,args:any[],map:(x:any)=>T):Promise<T>{const c=await this.openPlatform(context);try{const r=await c.query(sql,args);await c.query("COMMIT");const raw=sql.includes("SELECT security.platform_get")?r.rows[0]?.result:r.rows;return map(raw);}catch(e){await c.query("ROLLBACK");throw translate(e);}finally{c.release();}}
  private async openPlatform(context:PlatformSecurityContext){if(context.scopeKind!=="platform")throw new AppError("PERMISSION_DENIED","PlatformSecurityContext required");const c=await this.pool.connect();try{await c.query("BEGIN");await c.query(`SET LOCAL ROLE ${role(this.cpRole)}`);await c.query("SELECT set_config('airen.identity_id',$1,true),set_config('airen.tenant_id','',true),set_config('airen.location_id','',true),set_config('airen.correlation_id',$2,true)",[context.actorIdentityId,context.correlationId]);return c;}catch(e){await c.query("ROLLBACK");c.release();throw translate(e);}}
}
