import { Pool, type PoolClient } from "pg";
import type { AuditRecord, UnitOfWork } from "../../audit-events/src/index.ts";
import type { DomainEvent, SecurityContext } from "../../shared-contracts/src/index.ts";
import type {
  ComplianceEnvironmentClass,
  ComplianceSeverity,
  ComplianceTransaction,
  CorrectiveActionRecord,
  FoodSafetyCheckRecord,
  FoodSafetyControlMaterial,
  FoodSafetyOutcome,
  NonComplianceRecord,
  OperationalIncidentRecord
} from "../../ristoairen/src/compliance/haccp-compliance-incident-corrective-action.ts";

function assertRoleIdentifier(role:string):string{if(!/^[a-z_][a-z0-9_]*$/.test(role))throw new Error("Unsafe PostgreSQL role identifier");return role;}
function iso(value:unknown):string{return new Date(String(value)).toISOString();}
function optionalIso(value:unknown):string|undefined{return value==null?undefined:iso(value);}
function optionalString(value:unknown):string|undefined{return value==null?undefined:String(value);}

function controlFromRow(row:Record<string,unknown>):FoodSafetyControlMaterial{return Object.freeze({id:String(row.id),tenantId:String(row.tenantId),locationId:String(row.locationId),foodSafetyPlanId:String(row.foodSafetyPlanId),active:Boolean(row.active),rowVersion:Number(row.rowVersion),environmentClass:String(row.environmentClass) as ComplianceEnvironmentClass,planStatus:String(row.planStatus) as FoodSafetyControlMaterial["planStatus"],planEnvironmentClass:String(row.planEnvironmentClass) as ComplianceEnvironmentClass});}
function checkFromRow(row:Record<string,unknown>):FoodSafetyCheckRecord{return Object.freeze({id:String(row.id),tenantId:String(row.tenantId),locationId:String(row.locationId),controlDefinitionId:String(row.controlDefinitionId),...(row.scheduledFor==null?{}:{scheduledFor:iso(row.scheduledFor)}),performedAt:iso(row.performedAt),performedByIdentityId:String(row.performedByIdentityId),outcome:String(row.outcome) as FoodSafetyOutcome,...(row.measuredValueText==null?{}:{measuredValueText:String(row.measuredValueText)}),...(row.notes==null?{}:{notes:String(row.notes)}),...(row.evidenceReference==null?{}:{evidenceReference:String(row.evidenceReference)}),idempotencyKey:String(row.idempotencyKey),correlationId:String(row.correlationId),environmentClass:String(row.environmentClass) as ComplianceEnvironmentClass});}
function nonComplianceFromRow(row:Record<string,unknown>):NonComplianceRecord{return Object.freeze({id:String(row.id),tenantId:String(row.tenantId),locationId:String(row.locationId),foodSafetyCheckId:String(row.foodSafetyCheckId),severity:String(row.severity) as ComplianceSeverity,summary:String(row.summary),status:String(row.status) as NonComplianceRecord["status"],raisedAt:iso(row.raisedAt),raisedByIdentityId:String(row.raisedByIdentityId),correlationId:String(row.correlationId),environmentClass:String(row.environmentClass) as ComplianceEnvironmentClass});}
function incidentFromRow(row:Record<string,unknown>):OperationalIncidentRecord{return Object.freeze({id:String(row.id),tenantId:String(row.tenantId),locationId:String(row.locationId),incidentType:String(row.incidentType),severity:String(row.severity) as ComplianceSeverity,summary:String(row.summary),occurredAt:iso(row.occurredAt),reportedAt:iso(row.reportedAt),reportedByIdentityId:String(row.reportedByIdentityId),status:String(row.status) as OperationalIncidentRecord["status"],correlationId:String(row.correlationId),environmentClass:String(row.environmentClass) as ComplianceEnvironmentClass});}
function actionFromRow(row:Record<string,unknown>):CorrectiveActionRecord{return Object.freeze({id:String(row.id),tenantId:String(row.tenantId),locationId:String(row.locationId),...(row.nonComplianceId==null?{}:{nonComplianceId:String(row.nonComplianceId)}),...(row.operationalIncidentId==null?{}:{operationalIncidentId:String(row.operationalIncidentId)}),actionText:String(row.actionText),...(row.assignedToIdentityId==null?{}:{assignedToIdentityId:String(row.assignedToIdentityId)}),...(row.dueAt==null?{}:{dueAt:iso(row.dueAt)}),severity:String(row.severity) as ComplianceSeverity,status:String(row.status) as CorrectiveActionRecord["status"],...(row.closureSummary==null?{}:{closureSummary:String(row.closureSummary)}),...(row.closureEvidenceReference==null?{}:{closureEvidenceReference:String(row.closureEvidenceReference)}),...(row.closedAt==null?{}:{closedAt:iso(row.closedAt)}),...(row.closedByIdentityId==null?{}:{closedByIdentityId:String(row.closedByIdentityId)}),rowVersion:Number(row.rowVersion),correlationId:String(row.correlationId),environmentClass:String(row.environmentClass) as ComplianceEnvironmentClass});}

const CONTROL_SELECT=`SELECT c.id::text AS id,c.tenant_id::text AS "tenantId",c.location_id::text AS "locationId",c.food_safety_plan_id::text AS "foodSafetyPlanId",c.active,c.row_version AS "rowVersion",c.environment_class AS "environmentClass",p.status AS "planStatus",p.environment_class AS "planEnvironmentClass" FROM ristoairen.food_safety_control_definitions c JOIN ristoairen.food_safety_plans p ON p.tenant_id=c.tenant_id AND p.location_id=c.location_id AND p.id=c.food_safety_plan_id`;
const CHECK_SELECT=`SELECT id::text AS id,tenant_id::text AS "tenantId",location_id::text AS "locationId",control_definition_id::text AS "controlDefinitionId",scheduled_for AS "scheduledFor",performed_at AS "performedAt",performed_by_identity_id::text AS "performedByIdentityId",outcome,measured_value_text AS "measuredValueText",notes,evidence_reference AS "evidenceReference",idempotency_key AS "idempotencyKey",correlation_id AS "correlationId",environment_class AS "environmentClass" FROM ristoairen.food_safety_checks`;
const NON_COMPLIANCE_SELECT=`SELECT id::text AS id,tenant_id::text AS "tenantId",location_id::text AS "locationId",food_safety_check_id::text AS "foodSafetyCheckId",severity,summary,status,raised_at AS "raisedAt",raised_by_identity_id::text AS "raisedByIdentityId",correlation_id AS "correlationId",environment_class AS "environmentClass" FROM ristoairen.non_compliances`;
const INCIDENT_SELECT=`SELECT id::text AS id,tenant_id::text AS "tenantId",location_id::text AS "locationId",incident_type AS "incidentType",severity,summary,occurred_at AS "occurredAt",reported_at AS "reportedAt",reported_by_identity_id::text AS "reportedByIdentityId",status,correlation_id AS "correlationId",environment_class AS "environmentClass" FROM ristoairen.operational_incidents`;
const ACTION_SELECT=`SELECT id::text AS id,tenant_id::text AS "tenantId",location_id::text AS "locationId",non_compliance_id::text AS "nonComplianceId",operational_incident_id::text AS "operationalIncidentId",action_text AS "actionText",assigned_to_identity_id::text AS "assignedToIdentityId",due_at AS "dueAt",severity,status,closure_summary AS "closureSummary",closure_evidence_reference AS "closureEvidenceReference",closed_at AS "closedAt",closed_by_identity_id::text AS "closedByIdentityId",row_version AS "rowVersion",correlation_id AS "correlationId",environment_class AS "environmentClass" FROM ristoairen.corrective_actions`;

export class PostgresComplianceTransaction implements ComplianceTransaction {
  private readonly client:PoolClient;
  constructor(client:PoolClient){this.client=client;}

  async getControlDefinition(controlDefinitionId:string):Promise<FoodSafetyControlMaterial|null>{const r=await this.client.query(`${CONTROL_SELECT} WHERE c.id=$1::uuid`,[controlDefinitionId]);return r.rows[0]?controlFromRow(r.rows[0] as Record<string,unknown>):null;}
  async findCheckByIdempotencyKey(controlDefinitionId:string,idempotencyKey:string):Promise<FoodSafetyCheckRecord|null>{const r=await this.client.query(`${CHECK_SELECT} WHERE control_definition_id=$1::uuid AND idempotency_key=$2`,[controlDefinitionId,idempotencyKey]);return r.rows[0]?checkFromRow(r.rows[0] as Record<string,unknown>):null;}
  async getCheck(foodSafetyCheckId:string):Promise<FoodSafetyCheckRecord|null>{const r=await this.client.query(`${CHECK_SELECT} WHERE id=$1::uuid`,[foodSafetyCheckId]);return r.rows[0]?checkFromRow(r.rows[0] as Record<string,unknown>):null;}
  async insertCheck(input:Readonly<{tenantId:string;locationId:string;controlDefinitionId:string;scheduledFor?:string;performedAt:string;performedByIdentityId:string;outcome:FoodSafetyOutcome;measuredValueText?:string;notes?:string;evidenceReference?:string;idempotencyKey:string;correlationId:string;environmentClass:ComplianceEnvironmentClass}>):Promise<FoodSafetyCheckRecord>{const r=await this.client.query(`INSERT INTO ristoairen.food_safety_checks (tenant_id,location_id,control_definition_id,scheduled_for,performed_at,performed_by_identity_id,outcome,measured_value_text,notes,evidence_reference,idempotency_key,correlation_id,environment_class) VALUES ($1::uuid,$2::uuid,$3::uuid,$4::timestamptz,$5::timestamptz,$6::uuid,$7,$8,$9,$10,$11,$12,$13) RETURNING id::text AS id,tenant_id::text AS "tenantId",location_id::text AS "locationId",control_definition_id::text AS "controlDefinitionId",scheduled_for AS "scheduledFor",performed_at AS "performedAt",performed_by_identity_id::text AS "performedByIdentityId",outcome,measured_value_text AS "measuredValueText",notes,evidence_reference AS "evidenceReference",idempotency_key AS "idempotencyKey",correlation_id AS "correlationId",environment_class AS "environmentClass"`,[input.tenantId,input.locationId,input.controlDefinitionId,input.scheduledFor??null,input.performedAt,input.performedByIdentityId,input.outcome,input.measuredValueText??null,input.notes??null,input.evidenceReference??null,input.idempotencyKey,input.correlationId,input.environmentClass]);return checkFromRow(r.rows[0] as Record<string,unknown>);}

  async findNonComplianceByCheck(foodSafetyCheckId:string):Promise<NonComplianceRecord|null>{const r=await this.client.query(`${NON_COMPLIANCE_SELECT} WHERE food_safety_check_id=$1::uuid`,[foodSafetyCheckId]);return r.rows[0]?nonComplianceFromRow(r.rows[0] as Record<string,unknown>):null;}
  async getNonCompliance(nonComplianceId:string):Promise<NonComplianceRecord|null>{const r=await this.client.query(`${NON_COMPLIANCE_SELECT} WHERE id=$1::uuid`,[nonComplianceId]);return r.rows[0]?nonComplianceFromRow(r.rows[0] as Record<string,unknown>):null;}
  async insertNonCompliance(input:Readonly<{tenantId:string;locationId:string;foodSafetyCheckId:string;severity:ComplianceSeverity;summary:string;raisedAt:string;raisedByIdentityId:string;correlationId:string;environmentClass:ComplianceEnvironmentClass}>):Promise<NonComplianceRecord>{const r=await this.client.query(`INSERT INTO ristoairen.non_compliances (tenant_id,location_id,food_safety_check_id,severity,summary,status,raised_at,raised_by_identity_id,correlation_id,environment_class) VALUES ($1::uuid,$2::uuid,$3::uuid,$4,$5,'OPEN',$6::timestamptz,$7::uuid,$8,$9) RETURNING id::text AS id,tenant_id::text AS "tenantId",location_id::text AS "locationId",food_safety_check_id::text AS "foodSafetyCheckId",severity,summary,status,raised_at AS "raisedAt",raised_by_identity_id::text AS "raisedByIdentityId",correlation_id AS "correlationId",environment_class AS "environmentClass"`,[input.tenantId,input.locationId,input.foodSafetyCheckId,input.severity,input.summary,input.raisedAt,input.raisedByIdentityId,input.correlationId,input.environmentClass]);return nonComplianceFromRow(r.rows[0] as Record<string,unknown>);}

  async getIncident(operationalIncidentId:string):Promise<OperationalIncidentRecord|null>{const r=await this.client.query(`${INCIDENT_SELECT} WHERE id=$1::uuid`,[operationalIncidentId]);return r.rows[0]?incidentFromRow(r.rows[0] as Record<string,unknown>):null;}
  async insertIncident(input:Readonly<{tenantId:string;locationId:string;incidentType:string;severity:ComplianceSeverity;summary:string;occurredAt:string;reportedAt:string;reportedByIdentityId:string;correlationId:string;environmentClass:ComplianceEnvironmentClass}>):Promise<OperationalIncidentRecord>{const r=await this.client.query(`INSERT INTO ristoairen.operational_incidents (tenant_id,location_id,incident_type,severity,summary,occurred_at,reported_at,reported_by_identity_id,status,correlation_id,environment_class) VALUES ($1::uuid,$2::uuid,$3,$4,$5,$6::timestamptz,$7::timestamptz,$8::uuid,'OPEN',$9,$10) RETURNING id::text AS id,tenant_id::text AS "tenantId",location_id::text AS "locationId",incident_type AS "incidentType",severity,summary,occurred_at AS "occurredAt",reported_at AS "reportedAt",reported_by_identity_id::text AS "reportedByIdentityId",status,correlation_id AS "correlationId",environment_class AS "environmentClass"`,[input.tenantId,input.locationId,input.incidentType,input.severity,input.summary,input.occurredAt,input.reportedAt,input.reportedByIdentityId,input.correlationId,input.environmentClass]);return incidentFromRow(r.rows[0] as Record<string,unknown>);}

  async getCorrectiveAction(correctiveActionId:string):Promise<CorrectiveActionRecord|null>{const r=await this.client.query(`${ACTION_SELECT} WHERE id=$1::uuid`,[correctiveActionId]);return r.rows[0]?actionFromRow(r.rows[0] as Record<string,unknown>):null;}
  async lockCorrectiveAction(correctiveActionId:string):Promise<CorrectiveActionRecord|null>{const r=await this.client.query(`${ACTION_SELECT} WHERE id=$1::uuid FOR UPDATE`,[correctiveActionId]);return r.rows[0]?actionFromRow(r.rows[0] as Record<string,unknown>):null;}
  async insertCorrectiveAction(input:Readonly<{tenantId:string;locationId:string;nonComplianceId?:string;operationalIncidentId?:string;actionText:string;assignedToIdentityId?:string;dueAt?:string;severity:ComplianceSeverity;status:"OPEN"|"ASSIGNED";correlationId:string;environmentClass:ComplianceEnvironmentClass}>):Promise<CorrectiveActionRecord>{const r=await this.client.query(`INSERT INTO ristoairen.corrective_actions (tenant_id,location_id,non_compliance_id,operational_incident_id,action_text,assigned_to_identity_id,due_at,severity,status,row_version,correlation_id,environment_class) VALUES ($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5,$6::uuid,$7::timestamptz,$8,$9,1,$10,$11) RETURNING id::text AS id,tenant_id::text AS "tenantId",location_id::text AS "locationId",non_compliance_id::text AS "nonComplianceId",operational_incident_id::text AS "operationalIncidentId",action_text AS "actionText",assigned_to_identity_id::text AS "assignedToIdentityId",due_at AS "dueAt",severity,status,closure_summary AS "closureSummary",closure_evidence_reference AS "closureEvidenceReference",closed_at AS "closedAt",closed_by_identity_id::text AS "closedByIdentityId",row_version AS "rowVersion",correlation_id AS "correlationId",environment_class AS "environmentClass"`,[input.tenantId,input.locationId,input.nonComplianceId??null,input.operationalIncidentId??null,input.actionText,input.assignedToIdentityId??null,input.dueAt??null,input.severity,input.status,input.correlationId,input.environmentClass]);return actionFromRow(r.rows[0] as Record<string,unknown>);}
  async closeCorrectiveAction(input:Readonly<{correctiveActionId:string;expectedRowVersion:number;closureSummary:string;closureEvidenceReference?:string;closedAt:string;closedByIdentityId:string}>):Promise<CorrectiveActionRecord|null>{const r=await this.client.query(`UPDATE ristoairen.corrective_actions SET status='CLOSED',closure_summary=$2,closure_evidence_reference=$3,closed_at=$4::timestamptz,closed_by_identity_id=$5::uuid,row_version=row_version+1,updated_at=$4::timestamptz WHERE id=$1::uuid AND row_version=$6::integer AND status<>'CLOSED' RETURNING id::text AS id,tenant_id::text AS "tenantId",location_id::text AS "locationId",non_compliance_id::text AS "nonComplianceId",operational_incident_id::text AS "operationalIncidentId",action_text AS "actionText",assigned_to_identity_id::text AS "assignedToIdentityId",due_at AS "dueAt",severity,status,closure_summary AS "closureSummary",closure_evidence_reference AS "closureEvidenceReference",closed_at AS "closedAt",closed_by_identity_id::text AS "closedByIdentityId",row_version AS "rowVersion",correlation_id AS "correlationId",environment_class AS "environmentClass"`,[input.correctiveActionId,input.closureSummary,input.closureEvidenceReference??null,input.closedAt,input.closedByIdentityId,input.expectedRowVersion]);return r.rows[0]?actionFromRow(r.rows[0] as Record<string,unknown>):null;}

  async audit(record:AuditRecord):Promise<void>{await this.client.query(`INSERT INTO audit.audit_events (tenant_id,location_id,actor_identity_id,actor_kind,action_key,resource_type,resource_id,correlation_id,outcome,metadata) VALUES ($1::uuid,$2::uuid,$3::uuid,'system',$4,$5,$6,$7,$8,$9::jsonb)`,[record.tenantId,record.locationId,record.actorIdentityId,record.actionKey,record.resourceType??null,record.resourceId??null,record.correlationId,record.outcome,JSON.stringify(record.metadata??{})]);}
  async outbox(_event:DomainEvent & {tenantId:string;locationId:string;correlationId:string}):Promise<void>{throw new Error("MAT031_COMPLIANCE_HAS_NO_OUTBOX");}
}

export class PostgresComplianceUnitOfWork implements UnitOfWork<ComplianceTransaction> {
  private readonly pool:Pool;
  private readonly assumeRole:string;
  constructor(pool:Pool,assumeRole="airen_app"){this.pool=pool;this.assumeRole=assumeRole;}
  async transaction<T>(fn:(tx:ComplianceTransaction)=>Promise<T>,context?:SecurityContext):Promise<T>{
    if(!context)throw new Error("SecurityContext is required for MAT-031 compliance runtime");
    const client=await this.pool.connect();
    try{
      await client.query("BEGIN");
      await client.query(`SET LOCAL ROLE ${assertRoleIdentifier(this.assumeRole)}`);
      await client.query("SELECT set_config('airen.identity_id',$1,true),set_config('airen.tenant_id',$2,true),set_config('airen.location_id',$3,true),set_config('airen.correlation_id',$4,true)",[context.actorIdentityId,context.tenantId,context.locationId,context.correlationId]);
      const value=await fn(new PostgresComplianceTransaction(client));
      await client.query("COMMIT");
      return value;
    }catch(error){
      await client.query("ROLLBACK");
      throw error;
    }finally{client.release();}
  }
}
